In [1]:
import numpy as np
adw_traj1 = np.load("sample_adw/dataset/adw_traj1.npy")
print(adw_traj1.shape)
print(adw_traj1)

(500, 100, 1)
[[[-0.24308279]
  [ 1.16216337]
  [ 1.15409927]
  ...
  [ 0.37551958]
  [ 0.57444443]
  [ 0.24098899]]

 [[ 0.46676871]
  [ 0.38243221]
  [ 0.63251721]
  ...
  [ 0.57197266]
  [ 0.59321906]
  [ 0.2270376 ]]

 [[ 0.42368393]
  [-0.01535896]
  [-0.46090961]
  ...
  [ 0.44702397]
  [ 0.80299958]
  [ 0.47055704]]

 ...

 [[ 1.86444628]
  [ 2.58698442]
  [ 1.71737899]
  ...
  [-0.26328155]
  [ 0.15976094]
  [ 0.02401691]]

 [[-0.1032148 ]
  [ 0.00313787]
  [-0.26269559]
  ...
  [ 2.50274827]
  [ 2.82628165]
  [ 2.05517373]]

 [[ 1.25341273]
  [ 1.01249011]
  [ 1.48835797]
  ...
  [ 0.0268704 ]
  [ 0.73165271]
  [ 1.20698814]]]


In [2]:
!cat sample_adw/config_adw.json

In [3]:
!cat sample_adw/hyparam_adw.json

{
    "emission_internal_layers": [
        {
            "name": "fc",
            "dim_output": 32
        }
    ],
	"transition_internal_layers": [
        {
            "name": "fc"
        }
    ],
    "variational_internal_layers": [
        {
            "name": "lstm"
        },
        {
            "name": "fc"
        }
    ],
    "potential_internal_layers": [
        {
            "name": "fc"
        }
    ],
    "evaluation": {
        "all_costs": [
            0.0,
            0.0,
            0.0
        ],
        "cost": 0.0,
        "error": 0.0,
        "validation_all_costs": [
            0.0,
            0.0,
            0.0
        ],
        "validation_cost": 0.0
    },
    "evaluation_output": "sample_adw/model/hyparam.result.json",
    "plot_path": "sample_adw/model/plot",
    "save_model_path": "sample_adw/model/model",
    "save_result_filter": "sample_adw/model/result/filter.jbl",
    "save_result_test": "sample_adw/model/result/test.jbl",
    "save_res

In [4]:
!mkdir -p sample_adw/model 

In [6]:
!dmm --config sample_adw/config_adw.json\
--hyperparam sample_adw/hyparam_adw.json\
--save-config sample_adw/config.result.json train,test,filter


2020-07-01 15:16:28.942362: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-01 15:16:28.944567: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
#training data: 400
#valid data: 100
train_data_size: 400
batch_size     : 100
n_steps        : 100
dim_emit       : 1


The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed th

epoch 130, training cost 3.62593 (error=0.0223814), validation cost 3.65727 (error=0.0230779)
epoch 140, training cost 3.6259 (error=0.0223807), validation cost 3.65712 (error=0.023082)
epoch 150, training cost 3.62612 (error=0.0223834), validation cost 3.65725 (error=0.0230835)
epoch 160, training cost 3.62632 (error=0.0223877), validation cost 3.65766 (error=0.0230901)
epoch 170, training cost 3.62621 (error=0.0223862), validation cost 3.65741 (error=0.023085)
epoch 180, training cost 3.62593 (error=0.0223814), validation cost 3.65714 (error=0.0230808)
epoch 190, training cost 3.62593 (error=0.0223804), validation cost 3.65724 (error=0.0230811)
epoch 200, training cost 3.62591 (error=0.0223803), validation cost 3.65715 (error=0.0230802)
epoch 210, training cost 3.62593 (error=0.022381), validation cost 3.65713 (error=0.0230794)
epoch 220, training cost 3.62615 (error=0.022386), validation cost 3.65734 (error=0.023085)
epoch 230, training cost 3.62642 (error=0.022391), validation cost

In [7]:
!python script/plot_p.py --config ./sample_adw/config.result.json --hyperparam sample_adw/model/hyparam.result.json --limit_all 10 all 

==== save_result_filter
[LOAD]: sample_adw/model/result/filter.jbl
[LOAD]: sample_adw/dataset/adw_traj1.npy
z: (10, 500, 101, 2)
data index: 0
dimension (observation): 0
plotting dimension (latent): 0 - 1
steps: 100
[SAVE] : sample_adw/model/plot/0_data0_p.png
data index: 1
dimension (observation): 0
plotting dimension (latent): 0 - 1
steps: 100
[SAVE] : sample_adw/model/plot/1_data1_p.png
data index: 2
dimension (observation): 0
plotting dimension (latent): 0 - 1
steps: 100
[SAVE] : sample_adw/model/plot/2_data2_p.png
data index: 3
dimension (observation): 0
plotting dimension (latent): 0 - 1
steps: 100
[SAVE] : sample_adw/model/plot/3_data3_p.png
data index: 4
dimension (observation): 0
plotting dimension (latent): 0 - 1
steps: 100
[SAVE] : sample_adw/model/plot/4_data4_p.png
data index: 5
dimension (observation): 0
plotting dimension (latent): 0 - 1
steps: 100
[SAVE] : sample_adw/model/plot/5_data5_p.png
data index: 6
dimension (observation): 0
plotting dimension (latent): 0 - 1
ste

In [ ]:
!dmm --config sample_adw/config_adw.json\
--hyperparam sample_adw/hyparam_adw.json\
--save-config sample_adw/config.result.json test

In [ ]:
!dmm-plot train --config sample_adw/config.result.json --obs_dim 0

In [ ]:
display_png(Image("sample_adw/model/plot/116_data116_train.png"))

In [ ]:
!dmm-plot filter --config sample_adw/config.result.json --obs_dim 0 